// Apelidos/abreviações de livro (39k, "palpite de referência") — não existe
// esse dado em nenhum outro lugar do app (bibleBlocks.js só tem o nome
// completo, ver comentário em bibleSearch.js). Autoria própria, seguindo as
// abreviações padrão mais usadas em referências bíblicas em português e
// inglês (as mesmas formas que a própria autora usou como exemplo no
// pedido: "sl 23" -> Salmos, "jo 3.16" -> João) — não é um dado extraído de
// lugar nenhum, então cobre as formas mais comuns, não toda variação
// existente.
//
// Toda chave já é normalizada (normalizeForSearch: minúscula, sem acento)
// e todo valor é o nome CANÔNICO em português (o mesmo texto usado em
// `book`/completed_keys em todo o app — ver BIBLE_BLOCKS). O nome completo
// (português e inglês) de cada livro também vira alias automaticamente
// (ver bookAliasMap em bibleSearch.js) — este arquivo só guarda as formas
// ABREVIADAS, que não dá pra derivar do nome completo.
//
// Colisão conhecida e decidida: "Jó" e a abreviação usual de "João" ("Jo")
// normalizam pro mesmo texto ("jo") depois de tirar o acento — na prática,
// "Jo" quase sempre quer dizer João (é a forma da própria autora no
// pedido), então "jo" aponta pra João aqui. Pra Jó, a busca por NOME
// (não abreviação) continua funcionando normal via a lista de livros.
export const PT_BOOK_ABBREVIATIONS = {
  gn: 'Gênesis', gen: 'Gênesis',
  ex: 'Êxodo', exo: 'Êxodo', êx: 'Êxodo',
  lv: 'Levítico', lev: 'Levítico',
  nm: 'Números', num: 'Números',
  dt: 'Deuteronômio', deut: 'Deuteronômio',
  js: 'Josué', jos: 'Josué',
  jz: 'Juízes', jdz: 'Juízes', juiz: 'Juízes',
  rt: 'Rute',
  '1sm': '1 Samuel', '1 sm': '1 Samuel', '1sam': '1 Samuel', '1 sam': '1 Samuel',
  '2sm': '2 Samuel', '2 sm': '2 Samuel', '2sam': '2 Samuel', '2 sam': '2 Samuel',
  '1rs': '1 Reis', '1 rs': '1 Reis', '1re': '1 Reis',
  '2rs': '2 Reis', '2 rs': '2 Reis', '2re': '2 Reis',
  '1cr': '1 Crônicas', '1 cr': '1 Crônicas', '1cro': '1 Crônicas',
  '2cr': '2 Crônicas', '2 cr': '2 Crônicas', '2cro': '2 Crônicas',
  ed: 'Esdras', esd: 'Esdras',
  ne: 'Neemias', neh: 'Neemias',
  et: 'Ester', est: 'Ester',
  job: 'Jó',
  sl: 'Salmos', sal: 'Salmos', salmo: 'Salmos', salmos: 'Salmos', pv: 'Provérbios',
  prov: 'Provérbios', ec: 'Eclesiastes', ecl: 'Eclesiastes', cc: 'Cântico dos Cânticos',
  ct: 'Cântico dos Cânticos', cantares: 'Cântico dos Cânticos',
  is: 'Isaías', isa: 'Isaías',
  jr: 'Jeremias', jer: 'Jeremias',
  lm: 'Lamentações', lam: 'Lamentações',
  ez: 'Ezequiel', eze: 'Ezequiel',
  dn: 'Daniel', dan: 'Daniel',
  os: 'Oseias', ose: 'Oseias',
  jl: 'Joel',
  am: 'Amós', amo: 'Amós',
  ob: 'Obadias', oba: 'Obadias',
  jn: 'Jonas', jon: 'Jonas',
  mq: 'Miquéias', miq: 'Miquéias',
  na: 'Naum', nau: 'Naum',
  hc: 'Habacuque', hab: 'Habacuque',
  sf: 'Sofonias', sof: 'Sofonias',
  ag: 'Ageu',
  zc: 'Zacarias', zac: 'Zacarias',
  ml: 'Malaquias', mal: 'Malaquias',
  mt: 'Mateus', mat: 'Mateus',
  mc: 'Marcos', mar: 'Marcos',
  lc: 'Lucas', luc: 'Lucas',
  jo: 'João', joa: 'João',
  at: 'Atos', atos: 'Atos',
  rm: 'Romanos', rom: 'Romanos',
  '1co': '1 Coríntios', '1 co': '1 Coríntios', '1cor': '1 Coríntios',
  '2co': '2 Coríntios', '2 co': '2 Coríntios', '2cor': '2 Coríntios',
  gl: 'Gálatas', gal: 'Gálatas',
  ef: 'Efésios', efe: 'Efésios',
  fp: 'Filipenses', fil: 'Filipenses',
  cl: 'Colossenses', col: 'Colossenses',
  '1ts': '1 Tessalonicenses', '1 ts': '1 Tessalonicenses', '1tes': '1 Tessalonicenses',
  '2ts': '2 Tessalonicenses', '2 ts': '2 Tessalonicenses', '2tes': '2 Tessalonicenses',
  '1tm': '1 Timóteo', '1 tm': '1 Timóteo', '1tim': '1 Timóteo',
  '2tm': '2 Timóteo', '2 tm': '2 Timóteo', '2tim': '2 Timóteo',
  tt: 'Tito', tit: 'Tito',
  fm: 'Filemon', flm: 'Filemon',
  hb: 'Hebreus', heb: 'Hebreus',
  tg: 'Tiago', tia: 'Tiago',
  '1pe': '1 Pedro', '1 pe': '1 Pedro', '1ped': '1 Pedro',
  '2pe': '2 Pedro', '2 pe': '2 Pedro', '2ped': '2 Pedro',
  '1jo': '1 João', '1 jo': '1 João',
  '2jo': '2 João', '2 jo': '2 João',
  '3jo': '3 João', '3 jo': '3 João',
  jd: 'Judas', jud: 'Judas',
  ap: 'Apocalipse', apo: 'Apocalipse', apoc: 'Apocalipse',
}

// Mesma ideia em inglês — valores continuam o nome canônico em PORTUGUÊS
// (a chave de armazenamento de sempre), só as chaves (o que a pessoa
// digita) mudam de idioma.
export const EN_BOOK_ABBREVIATIONS = {
  gen: 'Gênesis', ge: 'Gênesis',
  exo: 'Êxodo', ex: 'Êxodo',
  lev: 'Levítico', lv: 'Levítico',
  num: 'Números', nu: 'Números',
  deu: 'Deuteronômio', dt: 'Deuteronômio', deut: 'Deuteronômio',
  jos: 'Josué', josh: 'Josué',
  jdg: 'Juízes', judg: 'Juízes',
  rut: 'Rute', ru: 'Rute',
  '1sa': '1 Samuel', '1 sa': '1 Samuel', '1sam': '1 Samuel', '1 sam': '1 Samuel',
  '2sa': '2 Samuel', '2 sa': '2 Samuel', '2sam': '2 Samuel', '2 sam': '2 Samuel',
  '1ki': '1 Reis', '1 ki': '1 Reis', '1kgs': '1 Reis',
  '2ki': '2 Reis', '2 ki': '2 Reis', '2kgs': '2 Reis',
  '1ch': '1 Crônicas', '1 ch': '1 Crônicas', '1chr': '1 Crônicas',
  '2ch': '2 Crônicas', '2 ch': '2 Crônicas', '2chr': '2 Crônicas',
  ezr: 'Esdras',
  neh: 'Neemias', ne: 'Neemias',
  est: 'Ester', es: 'Ester',
  job: 'Jó',
  ps: 'Salmos', psa: 'Salmos', psalm: 'Salmos', psalms: 'Salmos',
  pro: 'Provérbios', prov: 'Provérbios',
  ecc: 'Eclesiastes', eccl: 'Eclesiastes',
  sos: 'Cântico dos Cânticos', song: 'Cântico dos Cânticos', 'song of songs': 'Cântico dos Cânticos',
  isa: 'Isaías', is: 'Isaías',
  jer: 'Jeremias',
  lam: 'Lamentações',
  eze: 'Ezequiel', ezek: 'Ezequiel',
  dan: 'Daniel',
  hos: 'Oseias',
  joe: 'Joel', jl: 'Joel',
  amo: 'Amós', am: 'Amós',
  oba: 'Obadias', ob: 'Obadias',
  jon: 'Jonas',
  mic: 'Miquéias',
  nah: 'Naum',
  hab: 'Habacuque',
  zep: 'Sofonias', zeph: 'Sofonias',
  hag: 'Ageu',
  zec: 'Zacarias', zech: 'Zacarias',
  mal: 'Malaquias',
  mat: 'Mateus', matt: 'Mateus', mt: 'Mateus',
  mar: 'Marcos', mrk: 'Marcos', mk: 'Marcos',
  luk: 'Lucas', lk: 'Lucas',
  joh: 'João', jn: 'João',
  act: 'Atos', acts: 'Atos',
  rom: 'Romanos',
  '1co': '1 Coríntios', '1 co': '1 Coríntios', '1cor': '1 Coríntios',
  '2co': '2 Coríntios', '2 co': '2 Coríntios', '2cor': '2 Coríntios',
  gal: 'Gálatas',
  eph: 'Efésios',
  phi: 'Filipenses', phil: 'Filipenses', php: 'Filipenses',
  col: 'Colossenses',
  '1th': '1 Tessalonicenses', '1 th': '1 Tessalonicenses', '1thess': '1 Tessalonicenses',
  '2th': '2 Tessalonicenses', '2 th': '2 Tessalonicenses', '2thess': '2 Tessalonicenses',
  '1ti': '1 Timóteo', '1 ti': '1 Timóteo', '1tim': '1 Timóteo',
  '2ti': '2 Timóteo', '2 ti': '2 Timóteo', '2tim': '2 Timóteo',
  tit: 'Tito',
  phm: 'Filemon', phlm: 'Filemon',
  heb: 'Hebreus',
  jam: 'Tiago', jas: 'Tiago',
  '1pe': '1 Pedro', '1 pe': '1 Pedro', '1pet': '1 Pedro',
  '2pe': '2 Pedro', '2 pe': '2 Pedro', '2pet': '2 Pedro',
  '1jo': '1 João', '1 jo': '1 João', '1jn': '1 João',
  '2jo': '2 João', '2 jo': '2 João', '2jn': '2 João',
  '3jo': '3 João', '3 jo': '3 João', '3jn': '3 João',
  jud: 'Judas',
  rev: 'Apocalipse',
}
